### ISSUE TITLE
Choco install Fails prematurely

### ISSUE THREAD

**Issue by fasigpt** [nmallick1/AntaresBestPracticeAnalyzer-Windows#2]
If the user opens power shell without admin the installation of choco fails but it creates a folder c:\programdata\chocolatey with no content. Next time when you start the application , it only check for chocolatey folder and it assumes the tool is installed.
We need to check the size of the folder to make sure we reinstall chocolatey.

**Comment by nmallick1** [comment]
Changed to code to check for this condition. Thanks for reporting it.
